<a href="https://colab.research.google.com/github/vis-hal-k/Internship_Data_science/blob/main/DataScience_Topics/HyperParameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HyperParameter_tuning

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [15]:
pimaIn ="/content/drive/MyDrive/Colab Notebooks/DeepLearn-TopicsTheory-lab/HyperParameter_Tuning/Pima_Indian_tuning/diabetes.csv"

In [16]:
import numpy as np 
import pandas as pd

In [17]:
df = pd.read_csv(pimaIn)
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [18]:
df.shape

(768, 9)

In [19]:
df.corr()['Outcome']*100

Pregnancies                  22.189815
Glucose                      46.658140
BloodPressure                 6.506836
SkinThickness                 7.475223
Insulin                      13.054795
BMI                          29.269466
DiabetesPedigreeFunction     17.384407
Age                          23.835598
Outcome                     100.000000
Name: Outcome, dtype: float64

## Build The MODEL 

In [20]:
x = df.iloc[:, :-1].values
y = df.iloc[:,-1].values
display(x,y)

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [21]:
# Here we scale means all the value in range of -1 to 1 .
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x,x.shape

(array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
          0.46849198,  1.4259954 ],
        [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
         -0.36506078, -0.19067191],
        [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
          0.60439732, -0.10558415],
        ...,
        [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
         -0.68519336, -0.27575966],
        [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
         -0.37110101,  1.17073215],
        [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
         -0.47378505, -0.87137393]]),
 (768, 8))

In [22]:
from sklearn.model_selection import train_test_split 
x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state = 1) 

In [23]:
x_train , y_train, x_test, y_test

(array([[ 1.53084665,  0.75443236,  0.56322275, ...,  0.74976553,
          0.49869316,  0.57511787],
        [ 1.82781311,  0.25367803, -0.36733675, ...,  1.16859904,
         -0.0932501 ,  0.40494237],
        [ 0.93691372, -0.59134489,  0.25303625, ...,  0.66092205,
         -0.80901822,  1.00055664],
        ...,
        [ 2.7187125 ,  0.1597866 ,  1.08020025, ...,  1.44782138,
          0.33560676,  0.74529338],
        [ 0.04601433,  1.56815814,  0.14964075, ...,  1.47320522,
          0.02151441, -0.61611067],
        [ 1.53084665, -0.59134489,  0.35643175, ...,  0.1151693 ,
          0.58325649,  1.08564439]]),
 array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
   

In [73]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout
# from keras.layers import Dense,  

In [25]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam' , loss = 'binary_crossentropy',metrics =['accuracy'])

In [26]:
model.fit(x_train,y_train,batch_size=32 , epochs = 100 , validation_data=(x_test , y_test))

Epoch 1/100
20/20 [==============================] - 1s 19ms/step - loss: 0.6531 - accuracy: 0.6547 - val_loss: 0.6223 - val_accuracy: 0.6818
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6155 - accuracy: 0.6938 - val_loss: 0.5893 - val_accuracy: 0.7273
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5858 - accuracy: 0.7068 - val_loss: 0.5622 - val_accuracy: 0.7403
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5625 - accuracy: 0.7182 - val_loss: 0.5402 - val_accuracy: 0.7597
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5431 - accuracy: 0.7329 - val_loss: 0.5222 - val_accuracy: 0.7727
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5266 - accuracy: 0.7427 - val_loss: 0.5084 - val_accuracy: 0.7792
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5132 - accuracy: 0.7459 - val_loss: 0.4967 - val_accuracy: 0.7922
Epoch 8/100


In [27]:
# 1. How to select appropriate optimizer
# 2. Number of nodes in a layer
# 3. How to select no. of layers
# 4. All in one model

In [28]:
!pip install keras-tuner -q 

In [29]:
import keras_tuner as kt

In [30]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32 , activation = 'relu', input_dim=8))
  model.add(Dense(1,activation='sigmoid'))
  optimizer=hp.Choice('optimizer',values = ['adam','sgd','adagrad','rmsprop','adadelta'])
  model.compile(optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [31]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy' ,
                        max_trials=5
                        )
# This Grid search.

In [32]:
# there is many features in tuner but I mostly needed is search tuner
tuner.search(x_train , y_train , epochs=5 , validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.5324675440788269

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 09s


In [33]:
# This shows the best which is the optimizer
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [34]:
# from here we don't need to train the the model again. We can extract model from here 
#  num_models = 1 indicates best best accuracy model
model = tuner.get_best_models(num_models = 1)[0]
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(x_train,y_train , batch_size = 32 , epochs=100,initial_epoch = 6, validation_data =(x_test,y_test))

Epoch 7/100
20/20 [==============================] - 1s 11ms/step - loss: 0.5276 - accuracy: 0.7427 - val_loss: 0.5398 - val_accuracy: 0.7727
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5150 - accuracy: 0.7524 - val_loss: 0.5273 - val_accuracy: 0.7792
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5043 - accuracy: 0.7541 - val_loss: 0.5194 - val_accuracy: 0.7792
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4956 - accuracy: 0.7541 - val_loss: 0.5111 - val_accuracy: 0.7792
Epoch 11/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4890 - accuracy: 0.7557 - val_loss: 0.5053 - val_accuracy: 0.7857
Epoch 12/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4830 - accuracy: 0.7622 - val_loss: 0.5018 - val_accuracy: 0.7727
Epoch 13/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4781 - accuracy: 0.7671 - val_loss: 0.4982 - val_accuracy: 0.7727
Epoch 14

### Finding what is the right number of neuron we have to take ? 

In [36]:
def build_model(hp):
   model = Sequential()
   units = hp.Int('units',min_value=8,max_value=128,step=8)
  #  lowerLimit=8 , upperLimit =128 ||| 8->16->24->32--------------->128. that it run and give best out of these.
   model.add(Dense(units=units,activation='relu' , input_dim=8)) 
   model.add(Dense(1,activation='sigmoid'))
   model.compile(optimizer='rmsprop' , loss = 'binary_crossentropy' , metrics=['accuracy'])
   return model

In [37]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5 , directory = 'mydir')

In [38]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test , y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 17s


In [39]:
# This shows the best which is the optimizer
tuner.get_best_hyperparameters()[0].values
#  so here the best value is 96.

{'units': 96}

In [40]:
# Extract model at best accuracy
model = tuner.get_best_models(num_models=1)[0]
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 96)                864       
                                                                 
 dense_1 (Dense)             (None, 1)                 97        
                                                                 
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________


In [41]:
#  In this there are 96 neuron.
model.fit(x_train ,y_train, batch_size=32,epochs=100,initial_epoch=6, validation_data=(x_test,y_test) )

Epoch 7/100
20/20 [==============================] - 1s 11ms/step - loss: 0.4946 - accuracy: 0.7638 - val_loss: 0.4810 - val_accuracy: 0.8052
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4825 - accuracy: 0.7752 - val_loss: 0.4718 - val_accuracy: 0.8052
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4729 - accuracy: 0.7752 - val_loss: 0.4684 - val_accuracy: 0.8052
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4661 - accuracy: 0.7801 - val_loss: 0.4652 - val_accuracy: 0.8052
Epoch 11/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4613 - accuracy: 0.7736 - val_loss: 0.4630 - val_accuracy: 0.8117
Epoch 12/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4573 - accuracy: 0.7769 - val_loss: 0.4612 - val_accuracy: 0.8182
Epoch 13/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4544 - accuracy: 0.7834 - val_loss: 0.4594 - val_accuracy: 0.8117
Epoch 14

In [42]:
#  How to select number of layer
def build_model(hp):
  # 
  model=Sequential()
  # here we add first hidden layer
  model.add(Dense(72,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)): 
    # This for loops means the we create 10 models & in 1st model->1 layer , 1nd m ->2 layer, soon upto 10
    model.add(Dense(72,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop' , loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [43]:
tuner = kt.RandomSearch(build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name='num_layer'
)

In [44]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8181818127632141

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 09s


In [45]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 6}

In [48]:
model=tuner.get_best_models(num_models = 1)[0]
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 72)                648       
                                                                 
 dense_1 (Dense)             (None, 72)                5256      
                                                                 
 dense_2 (Dense)             (None, 72)                5256      
                                                                 
 dense_3 (Dense)             (None, 72)                5256      
                                                                 
 dense_4 (Dense)             (None, 72)                5256      
                                                                 
 dense_5 (Dense)             (None, 72)                5256      
                                                                 
 dense_6 (Dense)             (None, 72)                5

In [49]:
model.fit(x_train,y_train,epochs=100,initial_epoch=6,validation_data =(x_test,y_test))

Epoch 7/100
20/20 [==============================] - 1s 15ms/step - loss: 0.4718 - accuracy: 0.7655 - val_loss: 0.4832 - val_accuracy: 0.7857
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4611 - accuracy: 0.7752 - val_loss: 0.5060 - val_accuracy: 0.7727
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4556 - accuracy: 0.7752 - val_loss: 0.4906 - val_accuracy: 0.8052
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4407 - accuracy: 0.7932 - val_loss: 0.5174 - val_accuracy: 0.7532
Epoch 11/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4349 - accuracy: 0.7866 - val_loss: 0.4608 - val_accuracy: 0.8052
Epoch 12/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4266 - accuracy: 0.7948 - val_loss: 0.4717 - val_accuracy: 0.7987
Epoch 13/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3978 - accuracy: 0.8143 - val_loss: 0.4723 - val_accuracy: 0.8117
Epoch 14

In this accuray more decreases, 
we do final.

In [81]:
def build_model(hp):
  model=Sequential()
  counter=0
  for i in range(hp.Int('num_layer',min_value=1,max_value=10)):
    if counter==0:

      model.add(
          Dense(
              hp.Int('units'+str(i) , min_value=8,max_value=128,step=8),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),
              input_dim=8,
              )
       )
      model.add(Dropout(hp.Choice('dropout'+str(i) ,values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]))) 
    else:
      model.add(
          Dense(
              hp.Int('units'+str(i) , min_value=8,max_value=128,step=8),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])
              )
       )
      model.add(Dropout(hp.Choice('dropout'+str(i) ,values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
              
    counter+=1
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','sgd','nadam','adadelta']),
                loss='binary_crossentropy',metrics=['accuracy']
                )    
  return model

In [82]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3, 
                        directory="mydir",
                        project_name='final1'
                        )

In [83]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.649350643157959
Total elapsed time: 00h 00m 11s


In [84]:
tuner.get_best_hyperparameters()[0].values

{'num_layer': 5,
 'units0': 128,
 'activation0': 'relu',
 'dropout0': 0.9,
 'optimizer': 'nadam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'dropout4': 0.1}

In [85]:
# extract model
model = tuner.get_best_models(num_models=1)[0]

In [86]:
model.fit(x_train,y_train,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 7/100
20/20 [==============================] - 3s 14ms/step - loss: 0.6816 - accuracy: 0.6287 - val_loss: 0.6741 - val_accuracy: 0.6429
Epoch 8/100
20/20 [==============================] - 0s 6ms/step - loss: 0.6766 - accuracy: 0.6450 - val_loss: 0.6626 - val_accuracy: 0.6429
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6684 - accuracy: 0.6433 - val_loss: 0.6503 - val_accuracy: 0.6429
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6559 - accuracy: 0.6531 - val_loss: 0.6428 - val_accuracy: 0.6429
Epoch 11/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6493 - accuracy: 0.6498 - val_loss: 0.6340 - val_accuracy: 0.6429
Epoch 12/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6415 - accuracy: 0.6531 - val_loss: 0.6279 - val_accuracy: 0.6429
Epoch 13/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6263 - accuracy: 0.6531 - val_loss: 0.6209 - val_accuracy: 0.6429
Epoch 14