<a href="https://colab.research.google.com/github/vis-hal-k/Data_science_self-Practice/blob/main/DataScience_Topics/Pooling1D2D_max.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## MaxPooling-1D

In [1]:
import tensorflow as tf
from tensorflow import keras

In [3]:
tf.keras.layers.MaxPool2D(
    pool_size = (2,2),
    strides = None,
    padding='valid',
    data_format = None,
)

Downsamples the input representation by taking the maximum value over a spatial window of size pool_size. The window is shifted by `strides`. The resulting output, when using the `valid` padding option, has a shape of:

 `output_shape = (input_shape - pool_size + 1) / strides)`

The resulting output shape when using the **"same"** padding option is:

`output_shape = input_shape / strides`

For example, for `strides=1` and `padding="valid"`:

In [18]:
x = tf.constant([1.,2.,3.,4.,5.])
"""
The original input tensor x has a shape of (1, 5, 1),
where the first dimension represents the batch size,
the second dimension represents the length of the sequence,
and the third dimension represents the number of channels.
"""
x= tf.reshape(x,[1,5,1])
"""
The input tensor x is reshaped using tf.reshape to have a shape of (1, 5, 1).
This step is not relevant to the pooling operation but changes the shape
of the input tensor.
"""
x

'\nThe input tensor x is reshaped using tf.reshape to have a shape of (1, 5, 1).\nThis step is not relevant to the pooling operation but changes the shape \nof the input tensor.\n'

In [39]:
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 1 , padding = 'valid'
                                           )
featuremap = max_pool_1d(x)
"""
Padding is set to valid meand no Padding is added.
Using formula for final feature map is (n-f+1). similar as a kernel filter.
"""
featuremap.shape

TensorShape([1, 4, 1])

`For example, for stride=1 and padding="same"`

In [21]:
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x , [1,5,1])
# 1-> batch_size , 5-> input_size shape
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 2,
                                           padding='valid'
                                           )
"""
The formula use in this output_size = (input_size - pool_size) / stride + 1
so ((5-2)/2 + 1) = 2.5 takes as 2.
"""
max_pool_1d(x)

<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[2.],
        [4.]]], dtype=float32)>

`For example, for strides=1 and padding = “same”.`

Padding is `same` means padding is added.

In [42]:
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x , [1,5,1])
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 1 ,
                                           padding='same'
                                           )
'''
Same Padding: In this case, we add ‘p’ padding layers such that the output image has the same dimensions as the input image.
[(n + 2p) x (n + 2p) image] * [(f x f) filter] —> [(n x n) image]


Formula is using is output_size = (input_size + 2padding -pool_size)/strides + 1 .
p = 2-1 = 0.5
###### doubt #### ->  p is 0 or 1 (ceil or floor value.)
so output is  5+2*0.5-2 + 1 = 5 -> [1,5,1]
If we take strides = 2 then (5+2*0.5-2)/2 + 1 => 2+1 => 3
output is [1,3,1]

'''
max_pool_1d(x)


<tf.Tensor: shape=(1, 5, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.],
        [5.]]], dtype=float32)>

## MaxPooling_2D

In [44]:
tf.keras.layers.MaxPooling2D(
  pool_size = (2,2),
  strides = None ,
  padding = 'valid' ,
  data_format = None
)

Downsample the ainput along its sp[atial dimensions(height and width) by taking
the max value over an input window (of size define `pool_size`) for each channel of the inoput. The window is shifted by `strides` along each dimension.

The resulting output, when using the `"valid"` padding option, has a spatial shape(number of rows or columns) of:

`output_shape = math.floor((input_shape - pool_size)/strides) + 1`
when input_shape >= pool_size


***For same padding option***

The resulting output shape when using the `"same"` padding option id:

`output_shape = math.floor*((input_shape-1)/strides) + 1`



`For Example, for strides = (1,1)  and padding="valid"`

In [64]:
x = tf.constant([[1.,2.,3.],
               [4.,5.,6.],
                [7.,8.,9.]])
print(x,x.shape,x.ndim)
#        (3,3)  2
x = tf.reshape(x , [1,3,3,1])
print(x,x.shape,x.ndim)
# 1-> batch_size, 3-> rows , 3-> cols , 1-> channels


# max_pool_2d = tf.keras.layers.MaxPooling2D

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32) (3, 3) 2
tf.Tensor(
[[[[1.]
   [2.]
   [3.]]

  [[4.]
   [5.]
   [6.]]

  [[7.]
   [8.]
   [9.]]]], shape=(1, 3, 3, 1), dtype=float32) (1, 3, 3, 1) 4


In [65]:
[
  [
    [
      [1.],
      [2.],
      [3.]
    ],
    [
      [4.],
      [5.],
      [6.]
    ],
    [
      [7.],
      [8.],
      [9.]
    ]
  ]
]
"""
In this representation, each element within the innermost brackets [ ] represents a single value in the tensor.
The second dimension corresponds to the rows, while the third dimension corresponds to the columns.
So, based on this correct representation, the tensor has 1 batch, 3 rows, 3 columns, and 1 channel.
"""

[[[[1.0], [2.0], [3.0]], [[4.0], [5.0], [6.0]], [[7.0], [8.0], [9.0]]]]

`For example, for strides=(2, 2) and padding="valid":`

In [67]:
x = tf.constant([[1., 2., 3., 4.],
                 [5., 6., 7., 8.],
                 [9., 10., 11., 12.]])
x = tf.reshape(x, [1, 3, 4, 1])
print(x)
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(2, 2), padding='valid')
#  formula -> (n-f)/s + 1
max_pool_2d(x)

tf.Tensor(
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]]

  [[ 5.]
   [ 6.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [11.]
   [12.]]]], shape=(1, 3, 4, 1), dtype=float32)


<tf.Tensor: shape=(1, 1, 2, 1), dtype=float32, numpy=
array([[[[6.],
         [8.]]]], dtype=float32)>

`For example, for stride=(1, 1) and padding="same":`

Padding same means the dim of final image is same as input_image

In [70]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])
x = tf.reshape(x, [1, 3, 3, 1])
print(x)
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(1, 1), padding='same')
max_pool_2d(x)

tf.Tensor(
[[[[1.]
   [2.]
   [3.]]

  [[4.]
   [5.]
   [6.]]

  [[7.]
   [8.]
   [9.]]]], shape=(1, 3, 3, 1), dtype=float32)


<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[5.],
         [6.],
         [6.]],

        [[8.],
         [9.],
         [9.]],

        [[8.],
         [9.],
         [9.]]]], dtype=float32)>

*Note: Visualize convolutional operation while revesion.*