<a href="https://colab.research.google.com/github/vis-hal-k/Data_science_self-Practice/blob/main/DataScience_Topics/Pooling1D2D_max.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## MaxPooling-1D

In [1]:
import tensorflow as tf
from tensorflow import keras

In [3]:
tf.keras.layers.MaxPool2D(
    pool_size = (2,2),
    strides = None,
    padding='valid',
    data_format = None,
)

Downsamples the input representation by taking the maximum value over a spatial window of size pool_size. The window is shifted by `strides`. The resulting output, when using the `valid` padding option, has a shape of:

 `output_shape = (input_shape - pool_size + 1) / strides)`

The resulting output shape when using the **"same"** padding option is:

`output_shape = input_shape / strides`

For example, for `strides=1` and `padding="valid"`:

In [18]:
x = tf.constant([1.,2.,3.,4.,5.])
"""
The original input tensor x has a shape of (1, 5, 1),
where the first dimension represents the batch size,
the second dimension represents the length of the sequence,
and the third dimension represents the number of channels.
"""
x= tf.reshape(x,[1,5,1])
"""
The input tensor x is reshaped using tf.reshape to have a shape of (1, 5, 1).
This step is not relevant to the pooling operation but changes the shape
of the input tensor.
"""
x

'\nThe input tensor x is reshaped using tf.reshape to have a shape of (1, 5, 1).\nThis step is not relevant to the pooling operation but changes the shape \nof the input tensor.\n'

In [20]:
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 1 , padding = 'valid'
                                           )
featuremap = max_pool_1d(x)
"""
Padding is set to valid meand no Padding is added.
Using formula for final feature map is (n-f+1). similar as a kernel filter.
"""
featuremap.shape

TensorShape([1, 4, 1])

`For example, for stride=1 and padding="same"`

In [21]:
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x , [1,5,1])
# 1-> batch_size , 5-> input_size shape
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 2,
                                           padding='valid'
                                           )
"""
The formula use in this output_size = (input_size - pool_size) / stride + 1
so ((5-2)/2 + 1) = 2.5 takes as 2.
"""
max_pool_1d(x)

<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[2.],
        [4.]]], dtype=float32)>

`For example, for strides=1 and padding = “same”.`

Padding is `same` means padding is added.

In [37]:
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x , [1,5,1])
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size = 2,
                                           strides = 1 ,
                                           padding='same'
                                           )
'''
Same Padding: In this case, we add ‘p’ padding layers such that the output image has the same dimensions as the input image.
[(n + 2p) x (n + 2p) image] * [(f x f) filter] —> [(n x n) image]


Formula is using is output_size = (input_size + 2padding -pool_size)/strides + 1 .
p = 2-1 = 0.5
###### doubt #### ->  p is 0 or 1 (ceil or floor value.)
so output is  5+2*0.5-2 + 1 = 5 -> [1,5,1]

'''
max_pool_1d(x)


<tf.Tensor: shape=(1, 5, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.],
        [5.]]], dtype=float32)>