# Contents

1. Functions
2. File IO
3. Error Handling
4. Numpy

### Functions

Function is a group of related statements that perform a specific task.

Functions help break our program into smaller and modular chunks. As our program grows larger and larger, functions make it more organized and manageable.

It avoids repetition and makes code reusable.

Built In Functions: The functions which are already defined in Python. Ex - print

User Defined Functions : Which are defined explicitly by the user.

def function_name(parameters):

    """
    Doc String
    """

    Statement(s)

In [2]:
# We should not use a built func as the name of our custom function

# def print(n):
#     return n*2

In [1]:
print(2)

2


Comment the above code and Re-start the Kernel now

User Defined Functions:

keyword "def" marks the start of function header

Parameters (arguments) through which we pass values to a function. These are optional

A colon(:) to mark the end of funciton header

Doc string describe what the function does. This is optional

"return" statement to return a value from the function. This is optional

In [8]:
def xyz():
    print("This is a func without parameters")
    return 2

In [ ]:
# Find if a no is prime or not
# 10 lines

In [10]:
a = xyz()
print(a)

This is a func without parameters
2


In [11]:
def print_name(name):
    """ 
    This function prints the name
    """
    print("Hello " + str(name)) # Here I don't have a return statement
    # This func does not return anything - means it'll return none

In [17]:
def print_name_return(name):
    """ 
    This function prints the name
    """
    return "Hello " + str(name) # Here I don't have a return statement

Once we have defined a function, we can call it from anywhere

In [15]:
print_name('satish')

Hello satish


In [13]:
print_name()

TypeError: print_name() missing 1 required positional argument: 'name'

In [16]:
a = print_name('satish')
print(a)

Hello satish
None


In [18]:
print_name_return('satish')

'Hello satish'

In [19]:
a = print_name_return('satish')

In [20]:
print(a)

Hello satish


The first string after the function header is called the docstring and is short for documentation string.

Although optional, documentation is a good programming practice, always document your code

Doc string will be written in triple quotes so that docstring can extend up to multiple lines

In [21]:
print(print_name.__doc__) # print doc string of the function

 
    This function prints the name
    


The return statement is used to exit a function and go back to the place from where it was called.

Syntax:

return [expression]
-> return statement can contain an expression which gets evaluated and the value is returned.

-> if there is no expression in the statement or the return statement itself is not present inside a function, then the function will return None Object

In [7]:
# No return statement, so it should return NONE
def print_name(name):
    """ 
    This function prints the name
    """
    print("Hello " + str(name)) # Here I don't have a return statement

In [8]:
a = print_name("Satish")

Hello Satish


In [9]:
type(a)

NoneType

In [49]:
def add(a,b):
    print("This is a function to return addition")
    return (a+b)
    print("Program finished!")

In [50]:
add("star", "fish")

This is a function to return addition


'starfish'

In [51]:
add("star", 3)

This is a function to return addition


TypeError: can only concatenate str (not "int") to str

In [23]:
add(2,3)

This is a function to return addition


5

In [25]:
def get_sum(lst):
    
    """
    This function returns the sum of all the elements in a list
    """
    
    #initialize sum
    _sum = 0
    
    #iterating over the list
    for num in lst:
        _sum += num
    return _sum


In [26]:
s = get_sum([1, 2, 3, 4])
print(s)

10


In [27]:
#print doc string
print(get_sum.__doc__)



    This function returns the sum of all the elements in a list
    


In [ ]:
6, 36 = 6

In [28]:
def computeHCF(a, b):
    """
    Computing HCF of two numbers
    """
    smaller = b if a > b else a  #consice way of writing if else statement
    
    hcf = 1
    for i in range(2, smaller+1):
        if (a % i == 0) and (b % i == 0):
            hcf = i
    return hcf

num1 = 6
num2 = 36

print("H.C.F of {0} and {1} is: {2}".format(num1, num2, computeHCF(num1, num2)))

H.C.F of 6 and 36 is: 6


Function Arguments

In [30]:
def greet(name, msg):
    """
    This function greets to person with the provided message
    """
    print("Hello {0} , {1}".format(name, msg))

#call the function with arguments
greet("satish", "Good Morning")

# Name and msg are args of this function. I am passing value Satish in name and value Good morning in msg

Hello satish , Good Morning


In [31]:
greet("Good Morning", "satish")

Hello Good Morning , satish


In [32]:
#suppose if we pass one argument

greet("satish") #will get an error

TypeError: greet() missing 1 required positional argument: 'msg'

Default or Named Arguments

In [46]:
def greet(name, msg="Good Morning"):
    """
    This function greets to person with the provided message
    if message is not provided, it defaults to "Good Morning"
    """
    print("Hello {0} , {1}".format(name, msg))

greet("satish", "Good Night")


Hello satish , Good Night


In [47]:
greet(3, "good")

Hello 3 , good


In [48]:
greet("star", "good")

Hello star , good


In [34]:
#with out msg argument
greet("satish")

Hello satish , Good Morning


Named Argument and Positional Argument

Named argument can not be passed before a positional argument

Positional args are non default args and named args are default args

In [35]:
def greet(msg="Good Morning", name):
    """
    This function greets to person with the provided message
    if message is not provided, it defaults to "Good Morning"
    """
    print("Hello {0} , {1}".format(name, msg))

greet("satish", "Good Night")

SyntaxError: non-default argument follows default argument (4062500416.py, line 1)

Once we have a default argument, all the arguments to its right must also have default values.

def greet(msg="Good Morning", name)

#will get a SyntaxError : non-default argument follows default argument

Arbitrary Arguments

Sometimes, we do not know in advance the number of arguments that will be passed into a function.Python allows us to handle this kind of situation through function calls with arbitrary number of arguments.

In [40]:
def sum_of_numbers(*numbers):
    """
    This function greets all persons in the names tuple 
    """
    print(numbers)
    sum_=0
    for num in numbers:
        sum_+=num
    return sum_

sum_of_numbers(1,4,5, 6, 8, 10, 34)

(1, 4, 5, 6, 8, 10, 34)


68

In [41]:
print(sum_)

NameError: name 'sum_' is not defined

the input numbers is considered as a tuple

In [20]:
sum_of_numbers(1,4,5)

(1, 4, 5)


10

Lambda Functions

In Python, anonymous function is a function that is defined without a name.

While normal functions are defined using the def keyword, in Python anonymous functions are defined using the lambda keyword.

Lambda functions are used extensively along with built-in functions like filter(), map()

syntax:

lambda arguments: expression

In [44]:
double = lambda x: x*2

print(double(5))

10


In [45]:
def double(x):
    return x * 2

print(double(5))


10


In [24]:
#Example use with filter()
lst = [1, 2, 3, 4, 5]
even_lst = list(filter(lambda x: (x%2 == 0), lst))
print(even_lst)

[2, 4]


Example of Filter

The filter() method filters the given sequence with the help of a function that tests each element in the sequence to be true or not.

filter(function, sequence)

In [26]:
# The same example with help of a function

def even(n):
    if n % 2 == 0:
        return n
    else:
        return
    
even_list = list(filter(even, lst))
even_list

[2, 4]

In the above example, I am creating a func in the memory, but with lambda, no extra object is being created in the memory

In [52]:
#Example use with map()
lst = [1, 2, 3, 4, 5]
new_lst = list(map(lambda x: x ** 2, lst))
print(new_lst)

[1, 4, 9, 16, 25]


map() function returns a map object(which is an iterator) of the results after applying the given function to each item of a given iterable (list, tuple etc.)

map(fun, iterable or sequence)

In [28]:
# Python program to demonstrate working
# of map.

# Return double of n
def twice(n):
    return 2*n

# We double all numbers using map()
numbers = (1, 2, 3, 4)
result = map(twice, numbers)
print(list(result))


[2, 4, 6, 8]


### File IO

File is a named location on disk to store related information. It is used to permanently store data in a non-volatile memory (e.g. hard disk).

Since, random access memory (RAM) is volatile which loses its data when computer is turned off, we use files for future use of the data.

When we want to read from or write to a file we need to open it first. When we are done, it needs to be closed, so that resources that are tied with the file are freed.

File operation:

Open a file

Read or write (perform operation)

Close the file

Open a File

Python has a built-in function open() to open a file. This function returns a file object, also called a handle, as it is used to read or modify the file accordingly.

In [54]:
f = open(r'example.txt') #open file in current direcotry
# Make sure that file is there in this path
# This file should be in your current folder
# Else, you'll have to mention the absolute path rather than relative path

In [55]:
open('test.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

In [53]:
import os
os.getcwd()
# To know where you're currently

'C:\\Users\\infoobjects\\Documents\\Verzeo\\Python\\Lecture 4'

We can specify the mode while opening a file. In mode, we specify whether we want to read 'r', write 'w' or append 'a' to the file. We also specify if we want to open the file in text mode or binary mode.

'r' Open a file for reading. (default)

'w' Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists.

'x' Open a file for exclusive creation. If the file already exists, the operation fails.

'a' Open for appending at the end of the file without truncating it. Creates a new file if it does not exist.

't' Open in text mode. (default)

'b' Open in binary mode.

'+' Open a file for updating (reading and writing)

In [56]:
f = open('example.txt')
f.close()

In order to write into a file we need to open it in write 'w', append 'a' or exclusive creation 'x' mode.

We need to be careful with the 'w' mode as it will overwrite into the file if it already exists. All previous data are erased.

Writing a string or sequence of bytes (for binary files) is done using write() method. This method returns the number of characters written to the file.

Open the file example.txt to see the contents

In [73]:
f = open("example.txt", "w")

In [74]:
f.write("This is a First File\n")
f.write("Another two lines\n")
f.close()

Open the file now

Reading a File

There are various methods available for this purpose. We can use the read(size) method to read in size number of data. If size parameter is not specified, it reads and returns up to the end of the file.

In [59]:
f = open("example.txt", "r")
f.read()

'This is a First File\nContains two lines\nThis is a First File\nAnother two lines\n'

In [60]:
f.tell() # Tells me the position of file handle f in the file

83

In [62]:
f.read()

''

There is nothing further to be read. We have read the entire file

In [63]:
f = open("example.txt", "r")
f.read(4) #Reading first 4 bytes only

'This'

In [64]:
f.read(5) # Reading next 10 bytes

' is a'

In [65]:
f.read() # Will read from the current file handle position till the end

' First File\nContains two lines\nThis is a First File\nAnother two lines\n'

In [66]:
f.seek(0) #bring the file cursor to initial position

0

In [67]:
f.read()

'This is a First File\nContains two lines\nThis is a First File\nAnother two lines\n'

In [68]:
f.close()

In [69]:
f = open("example.txt", "r")
f.readline() # To read an entire line

'This is a First File\n'

In [70]:
f.readline()

'Contains two lines\n'

In [71]:
# If I want to read all the lines one by one

f.seek(0)
f.readlines() # Will give me a list of all the lines

['This is a First File\n',
 'Contains two lines\n',
 'This is a First File\n',
 'Another two lines\n']

In [72]:
# If I want to read all the lines one by one
f.seek(0)
for line in f.readlines():
    print(line)

This is a First File

Contains two lines

This is a First File

Another two lines



### Error Handling

When writing a program, we, more often than not, will encounter errors.

Error caused by not following the proper structure (syntax) of the language is called syntax error or parsing error.

In [75]:
if a < 3

SyntaxError: invalid syntax (3603636323.py, line 1)

In [76]:
# Error stops the execution of our program

if a < 3
print("Hello")

SyntaxError: invalid syntax (2373150945.py, line 3)

Errors can also occur at runtime and these are called exceptions.

They occur, for example, when a file we try to open does not exist (FileNotFoundError), dividing a number by zero (ZeroDivisionError), module we try to import is not found (ImportError) etc.

Whenever these type of runtime error occur, Python creates an exception object. If not handled properly, it prints a traceback to that error along with some details about why that error occurred.

In [77]:
1 / 0

ZeroDivisionError: division by zero

In [78]:
open('test.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

In [79]:
#Python built in exceptions

dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

Error Handling

Python has many built-in exceptions which forces your program to output an error when something in it goes wrong.

When these exceptions occur, it causes the current process to stop and passes it to the calling process until it is handled. If not handled, our program will crash.

For example, if function A calls function B which in turn calls function C and an exception occurs in function C. If it is not handled in C, the exception passes to B and then to A.

If never handled, an error message is spit out and our program come to a sudden, unexpected halt.

In Python, exceptions can be handled using a try statement.

A critical operation which can raise exception is placed inside the try clause and the code that handles exception is written in except clause.

In [80]:
print("Division by a number")

a = 10
b = 0

try:
    a/b
    
except:
    print("There is something wrong")
    
print("Finished!")

Division by a number
There is something wrong
Finished!


In [81]:
# But I want to know what is wrong
# Use sys.exec_info
import sys
try:
    r = a/b
except:
    print("Oops!", sys.exc_info()[0],"occured.")
    print("Try again")

Oops! <class 'ZeroDivisionError'> occured.
Try again


In [27]:
# With except, we catch all the possible errors

In the above example, we did not mention any exception in the except clause.

This is not a good programming practice as it will catch all exceptions and handle every case in the same way. We can specify which exceptions an except clause will catch.

A try clause can have any number of except clause to handle them differently but only one will be executed in case an exception occurs.

In [82]:
import sys

lst = ['b', 0, 2] # I want to create a program to give me inverse of every element in a list

for entry in lst:
    try:
        print("****************************")
        print("The entry is", entry)
        r = 1 / int(entry)
    except(ValueError):
        print("Oops!", sys.exc_info()[0],"occured.")
    except(ZeroDivisionError):
        print("Oops!", sys.exc_info()[0],"occured.")
    except:
        print("Some other error")
print("The reciprocal of", entry, "is", r)

****************************
The entry is b
Oops! <class 'ValueError'> occured.
****************************
The entry is 0
Oops! <class 'ZeroDivisionError'> occured.
****************************
The entry is 2
The reciprocal of 2 is 0.5


The try statement in Python can have an optional finally clause. This clause is executed no matter what, and is generally used to release external resources.

In [83]:
try:
    f = open('sample.txt')
    #perform file operations
except FileNotFoundError:
    f = open('sample.txt', 'w')
    f.write("This is a sample file")
    
finally:
    f.close()

### Numpy

In [1]:
!pip install numpy

Arrays

python objects:

high-level number objects: integers, floating point

containers: lists (costless insertion and append), dictionaries (fast lookup)

Numpy provides:

extension package to Python for multi-dimensional arrays

closer to hardware (efficiency)

designed for scientific computation (convenience)

Also known as array oriented computing

In [84]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

# print(np.arange(10))

[0 1 2 3]


Why it is useful: Memory-efficient container that provides fast numerical operations.

In [ ]:
[[]]

In [4]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

310 µs ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [85]:
a = np.arange(1000)
# %timeit a**2

In [86]:
type(a)

numpy.ndarray

Creating Arrays

In [87]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [88]:
#print dimensions

a.ndim

1

In [89]:
#shape

a.shape

(4,)

In [90]:
len(a)

4

In [91]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
b.ndim

2

In [93]:
b.shape

(2, 3)

In [94]:
len(b) #returns the size of the first dimention

2

In [95]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [96]:
len(c)

2

In [97]:
c.ndim

3

In [98]:
c.shape

(2, 2, 2)

In [99]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [104]:
#using linspace

a = np.linspace(0, 1, 10) #start, end, number of points including start and end
# End is inclusive here

a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [107]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
a.dtype

dtype('float64')

In [102]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

You may have noticed that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:

In [105]:
a = np.arange(10)

a.dtype

dtype('int32')

In [106]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [109]:
a = np.arange(10)
print(a)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

[0 1 2 3 4 5 6 7 8 9]
5


In [110]:
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [112]:
a = np.diag([1, 2, 3])
print(a)
print(a[2, 2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [113]:
a[2, 1] = 5 # re-assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [29]:
a[1:, 1:]

array([[2, 0],
       [5, 3]])

In [30]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [31]:
a ** 2 # Element wise operations

array([ 1,  4,  9, 16], dtype=int32)

In [114]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [116]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [117]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [118]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

In [36]:
# similarly, I can use min, max, mean, std etc

In [119]:
x.mean(axis=0) 

array([1.5, 1.5])

In [38]:
x.mean(axis=1) 

array([1., 2.])